name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Prepare Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn run build

      - name: Upload theme artifacts
        uses: actions/upload-artifact@v4
        with:
          name: theme
          path: |
            acf-json
            assets
            dist
            inc
            parts
            templates
            *.php
            *.css
            *.png

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download theme artifacts
        uses: actions/download-artifact@v4
        with:
          name: theme
          path: theme

      - name: Create a zip file of theme directory
        run: zip -r theme.zip theme

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload theme.zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: theme.zip
          asset_name: theme.zip
          asset_content_type: application/zip
